// @vitest-environment jsdom
import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";
import {
  AI_PREVIEW_TEXT,
  AiPreviewNote,
  SHADE_ACCURACY_TEXT,
  ShadeAccuracyNote,
} from "../accuracy-note";

/**
 * These two sentences are the site's only defence against the two complaints this
 * product can actually attract: "the paint doesn't look like the screen" and "the AI
 * didn't get my wall right". They are pinned here because the risk with a disclaimer
 * is never that someone deletes it deliberately — it is that a page gets rewritten
 * and the note quietly goes with it, or the wording softens until it promises again.
 */
describe("accuracy notes", () => {
  it("says where shade colours come from and that they can differ", () => {
    expect(SHADE_ACCURACY_TEXT).toMatch(/shade cards/i);
    expect(SHADE_ACCURACY_TEXT).toMatch(/fan decks/i);
    expect(SHADE_ACCURACY_TEXT).toMatch(/can differ/i);
    // And tells the reader what to actually do about it.
    expect(SHADE_ACCURACY_TEXT).toMatch(/before you buy/i);
  });

  it("says previews are AI-made and not guaranteed", () => {
    expect(AI_PREVIEW_TEXT).toMatch(/generated by AI/i);
    expect(AI_PREVIEW_TEXT).toMatch(/not guaranteed/i);
    // "A guide, not an exact picture" is the claim limit — never "accurate".
    expect(AI_PREVIEW_TEXT).toMatch(/not an\s+exact/i);
  });

  it("renders each note on its own", () => {
    const { unmount } = render(<ShadeAccuracyNote />);
    expect(screen.getByRole("note").textContent).toBe(SHADE_ACCURACY_TEXT);
    unmount();

    render(<AiPreviewNote />);
    expect(screen.getByRole("note").textContent).toBe(AI_PREVIEW_TEXT);
  });

  /** Pages showing shades AND previews (the kiosk, a share link) need both. */
  it("renders both together when asked", () => {
    render(<ShadeAccuracyNote both />);
    const text = screen.getByRole("note").textContent ?? "";
    expect(text).toContain(SHADE_ACCURACY_TEXT);
    expect(text).toContain(AI_PREVIEW_TEXT);
  });
});
