import type { CSSProperties } from "react";

/**
 * The two things a customer must be told before they buy paint on the strength of
 * something they saw here.
 *
 * Both are written once and used everywhere, because the risk in a disclaimer is not
 * that it is missing from the terms — it is that the wording drifts, and a page ends
 * up promising more than the page next to it. Import these; do not retype them.
 *
 * They are deliberately short and plainly worded. A warning nobody reads protects
 * nobody, so each is one or two sentences saying exactly what could be different and
 * what to do about it.
 */

/** Colour on a screen is not paint on a wall. Show this wherever shades are shown. */
export const SHADE_ACCURACY_TEXT =
  "Shade colours are taken from the paint companies' own shade cards and fan decks. "
  + "Screens, printing and lighting all shift colour, so what you see here can differ "
  + "from the paint on the wall. Always check the physical shade card at the counter "
  + "before you buy.";

/** A preview is a guide, not a photograph of the finished room. */
export const AI_PREVIEW_TEXT =
  "Previews are generated by AI. They are a guide to how a colour might look, not an "
  + "exact picture of the finished wall — edges, textures and lighting can come out "
  + "differently, and results are not guaranteed.";

const baseStyle: CSSProperties = {
  font: "400 13px/1.6 var(--sans)",
  color: "var(--fg-mute)",
  margin: 0,
  maxWidth: "72ch",
};

interface NoteProps {
  style?: CSSProperties;
  /** Renders both notes as one paragraph — for pages that show shades AND previews. */
  both?: boolean;
}

/** "Colours may vary from the real paint." */
export function ShadeAccuracyNote({ style, both = false }: NoteProps) {
  return (
    <p role="note" style={{ ...baseStyle, ...style }}>
      {SHADE_ACCURACY_TEXT}
      {both ? " " + AI_PREVIEW_TEXT : null}
    </p>
  );
}

/** "The preview is AI-generated and not guaranteed." */
export function AiPreviewNote({ style }: { style?: CSSProperties }) {
  return (
    <p role="note" style={{ ...baseStyle, ...style }}>
      {AI_PREVIEW_TEXT}
    </p>
  );
}
