import Link from "next/link";
import { contact } from "@/lib/config";
import { libraryHasRooms } from "@/lib/free-projects-server";
import { SHOWCASE_CONTENT } from "@/lib/showcase";
import { BrandMark } from "./brand-mark";

// Our work and Journal are placeholder editorial pages and 404 unless
// NEXT_PUBLIC_SHOWCASE_CONTENT=1 (see lib/showcase) — don't link to a 404.
//
// Gallery is no longer one of them. It lists the rooms an admin has published and
// opens by itself once the shelf is not empty, so its link follows the shelf too
// — see the note in nav.tsx, which makes the same decision for the header.
function columnsFor(galleryLive: boolean) {
  return [
    {
      title: "Product",
      links: [
        { href: "/method", label: "How it works" },
        { href: "/catalogue", label: "Catalogue" },
        ...(SHOWCASE_CONTENT || galleryLive ? [{ href: "/gallery", label: "Gallery" }] : []),
        { href: "/pricing", label: "Pricing" },
      ],
    },
    {
      title: "Company",
      links: [
        ...(SHOWCASE_CONTENT
          ? [
              { href: "/work", label: "Our work" },
              { href: "/journal", label: "Journal" },
            ]
          : []),
        { href: "/legal/about", label: "About us" },
        { href: "/legal/contact", label: "Contact" },
      ],
    },
  ];
}

/**
 * Async so it can ask whether the gallery has anything on it.
 *
 * A server component throughout — it is rendered by ~20 pages, all of them server
 * components, and asking here rather than taking a prop keeps those pages from
 * having to thread an answer none of them care about. The read is a tagged,
 * revalidated fetch shared with the header, so it costs a cache hit.
 */
export async function Footer() {
  const galleryLive = await libraryHasRooms();
  const COLUMNS = columnsFor(galleryLive);
  return (
    <footer>
      <div className="footer-inner">
        <div className="footer-col">
          <Link
            href="/"
            aria-label="HueVista — home"
            style={{ display: "inline-flex", alignItems: "center", gap: 11, marginBottom: 16 }}
          >
            <BrandMark height={30} />
            <span style={{ display: "inline-block" }}>
              <span style={{ display: "block", font: "700 18px/1 var(--serif)", letterSpacing: "-.02em", color: "var(--fg)" }}>
                HueVista
              </span>
              <span
                style={{
                  display: "block",
                  marginTop: 5,
                  font: "400 12px/1 var(--mono)",
                  letterSpacing: ".2em",
                  textTransform: "uppercase",
                  color: "var(--fg-mute)",
                }}
              >
                Shades &amp; colours
              </span>
            </span>
          </Link>
          <p className="body" style={{ fontSize: 14, maxWidth: "34ch", marginTop: 12, color: "var(--fg-mute)" }}>
            Preview any paint colour on real walls before the can opens.
            Built in India for paint shops and their customers.
          </p>
          <address style={{ fontStyle: "normal", fontSize: 12.5, lineHeight: 1.6, marginTop: 18, color: "var(--fg-mute)", maxWidth: "34ch" }}>
            <div style={{ fontWeight: 600, color: "var(--fg-soft)" }}>HueVista</div>
            <div>Proprietor: Vikram Mali</div>
            <div>Mount Road, Manpur, Abu Road,{" "}<br />Sirohi, Rajasthan 307026, India</div>
            <div style={{ marginTop: 6 }}>
              <a href={`mailto:${contact.general}`} style={{ color: "inherit" }}>{contact.general}</a>
            </div>
            <div>
              <a href={`tel:${contact.phoneE164}`} style={{ color: "inherit" }}>{contact.phone}</a>
            </div>
          </address>
        </div>
        {COLUMNS.map((col) => (
          <div className="footer-col" key={col.title}>
            <div className="footer-col-title">{col.title}</div>
            {col.links.map((l, i) =>
              l.href.startsWith("mailto:") ? (
                <a key={`${l.href}-${i}`} href={l.href}>{l.label}</a>
              ) : (
                <Link key={`${l.href}-${i}`} href={l.href}>{l.label}</Link>
              ),
            )}
          </div>
        ))}
      </div>
      {/* On every page, in the place a reviewer looks for it. The independence line
          and the "colours may vary" line are the two claims the site has to stand
          behind everywhere, not only where shades happen to be on screen. */}
      <div className="footer-note">
        HueVista is an independent product and is not associated with, endorsed by or
        acting for any paint company; company and shade names are their owners&rsquo;
        trademarks, used only to identify a shade. Shade colours come from the
        companies&rsquo; own shade cards and previews are generated by AI, so both can
        differ from the paint on your wall — always check the physical shade card
        before you buy.
      </div>
      <div className="footer-bottom">
        <span className="mono">© 2026 HueVista</span>
        <span className="mono">Abu Road · Rajasthan · India</span>
        <span className="mono" style={{ display: "inline-flex", gap: 8 }}>
          <Link href="/legal/privacy" style={{ color: "inherit" }}>Privacy</Link>·
          <Link href="/legal/terms" style={{ color: "inherit" }}>Terms</Link>·
          <Link href="/legal/refunds" style={{ color: "inherit" }}>Refunds</Link>·
          <Link href="/legal/delivery" style={{ color: "inherit" }}>Delivery</Link>·
          <Link href="/legal/contact" style={{ color: "inherit" }}>Contact</Link>
        </span>
      </div>
    </footer>
  );
}
